#/bin/bash

REPORTMAILBLOCKCOUNT=""
REPORTMAILBLOCKCOUNTRECIPIENTS=""

# MONKEY EXPLORER BLOCKCOUNT
BLOCKCOUNTMONKEXPLORER=""
BLOCKCOUNTMONKEXPLORER=$(curl -s4 http://explorer.monkey.community/api/getblockcount)	
# echo $BLOCKCOUNTMONKEXPLORER

# COIN EXPLORER BLOCKCOUNT
BLOCKCOINEXPLORERMONK=""
BLOCKCOUNTCOINEXPLORERMONK=""
LASTBLOCKCOINEXPLORERMONK=""
LASTBLOCKCOINEXPLORERMONK=$(curl -s4 https://www.coinexplorer.net/api/MONK/block/latest)
# echo $LASTBLOCKCOINEXPLORERMONK
BLOCKCOUNTCOINEXPLORERMONK=', ' read -r -a array <<< $LASTBLOCKCOINEXPLORERMONK
BLOCKCOUNTCOINEXPLORERMONK=${array[8]}
# echo $BLOCKCOUNTCOINEXPLORERMONK
BLOCKCOUNTCOINEXPLORERMONK=$(echo $BLOCKCOUNTCOINEXPLORERMONK | tr , " ")
# echo $BLOCKCOUNTCOINEXPLORERMONK
BLOCKCOUNTCOINEXPLORERMONK=$(echo $BLOCKCOUNTCOINEXPLORERMONK | tr '"' " ")
# echo $BLOCKCOUNTCOINEXPLORERMONK
# echo -e "BLOCKCOUNTCOINEXPLORERMONK='${BLOCKCOUNTCOINEXPLORERMONK}'"
BLOCKCOUNTCOINEXPLORERMONK="$(echo -e "${BLOCKCOUNTCOINEXPLORERMONK}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
# echo -e "BLOCKCOUNTCOINEXPLORERMONK='${BLOCKCOUNTCOINEXPLORERMONK}'"

# MONK SEED 1 BLOCKCOUNT
BLOCKINFOMONKSEED_1=""
BLOCKINFOMONKSEED_1=$(curl -s4 http://nsseed1.monkey.vision/blockinfo.txt)	
# echo $BLOCKINFOMONKSEED_1
BLOCKCOUNTMONKSEED_1=', ' read -r -a array <<< $BLOCKINFOMONKSEED_1
BLOCKCOUNTMONKSEED_1=${array[18]}
# echo $BLOCKCOUNTMONKSEED_1
BLOCKCOUNTMONKSEED_1=$(echo $BLOCKCOUNTMONKSEED_1 | tr , " ")
BLOCKCOUNTMONKSEED_1="$(echo -e "${BLOCKCOUNTMONKSEED_1}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
# echo -e "BLOCKCOUNTMONKSEED_1='${BLOCKCOUNTMONKSEED_1}'"

# MONK SEED 2 BLOCKCOUNT
BLOCKINFOMONKSEED_2=""
BLOCKINFOMONKSEED_2=$(curl -s4 http://nsseed2.monkey.vision/blockinfo.txt)	
# echo $BLOCKINFOMONKSEED_2
BLOCKCOUNTMONKSEED_2=', ' read -r -a array <<< $BLOCKINFOMONKSEED_2
BLOCKCOUNTMONKSEED_2=${array[18]}
# echo $BLOCKCOUNTMONKSEED_2
BLOCKCOUNTMONKSEED_2=$(echo $BLOCKCOUNTMONKSEED_2 | tr , " ")
BLOCKCOUNTMONKSEED_2="$(echo -e "${BLOCKCOUNTMONKSEED_2}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
# echo -e "BLOCKCOUNTMONKSEED_2='${BLOCKCOUNTMONKSEED_2}'"

echo "*******************************************************"
echo **1. CHECKING SEED ONE AND SEED TWO**
echo "BLOCKCOUNTMONKSEED_1="$BLOCKCOUNTMONKSEED_1
echo "BLOCKCOUNTMONKSEED_2="$BLOCKCOUNTMONKSEED_2
# BLOCKCOUNTMONKSEED_2=$[BLOCKCOUNTMONKSEED_2 + 1] # testing :)
if [ "$BLOCKCOUNTMONKSEED_1" == "$BLOCKCOUNTMONKSEED_2" ]; then
	echo "SEED ONE AND SEED TWO = OK"
	# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo "SEED ONE AND SEED TWO = OK;")
else
	BLOCKCOUNTMONKSEED_2=$[BLOCKCOUNTMONKSEED_2 + 1]
	if [ "$BLOCKCOUNTMONKSEED_1" == "$BLOCKCOUNTMONKSEED_2" ]; then
		echo "SEED ONE AND SEED TWO = OK"
		# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo "SEED ONE AND SEED TWO = OK;")
		BLOCKCOUNTMONKSEED_2=$[BLOCKCOUNTMONKSEED_2 - 1]
	else
		BLOCKCOUNTMONKSEED_2=$[BLOCKCOUNTMONKSEED_2 - 2]
		if [ "$BLOCKCOUNTMONKSEED_1" == "$BLOCKCOUNTMONKSEED_2" ]; then
			echo "SEED ONE AND SEED TWO = OK"
			# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo "SEED ONE AND SEED TWO = OK;")		
			BLOCKCOUNTMONKSEED_2=$[BLOCKCOUNTMONKSEED_2 + 1]
		else
			echo "SEED ONE AND SEED TWO NOT MATCH !!!"
			REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo "SEED ONE AND SEED TWO NOT MATCH !!!;")
		fi
	fi
fi

echo "*******************************************************"
echo **2. CHECKING MONK EXPLORER AND COIN EXPLORER MONK**
echo "BLOCKCOUNTMONKEXPLORER="$BLOCKCOUNTMONKEXPLORER
echo "BLOCKCOUNTCOINEXPLORERMONK="$BLOCKCOUNTCOINEXPLORERMONK
# BLOCKCOUNTCOINEXPLORERMONK=$[BLOCKCOUNTCOINEXPLORERMONK + 1] # testing :)
if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTCOINEXPLORERMONK" ]; then
	echo "MONK EXPLORER AND COIN EXPLORER MONK = OK"
	# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND COIN EXPLORER MONK = OK;")
else	
	BLOCKCOUNTCOINEXPLORERMONK=$[BLOCKCOUNTCOINEXPLORERMONK + 1]
	if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTCOINEXPLORERMONK" ]; then
		echo "MONK EXPLORER AND COIN EXPLORER MONK = OK"
		# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND COIN EXPLORER MONK = OK;")
		BLOCKCOUNTCOINEXPLORERMONK=$[BLOCKCOUNTCOINEXPLORERMONK - 1]
	else
		BLOCKCOUNTCOINEXPLORERMONK=$[BLOCKCOUNTCOINEXPLORERMONK - 2]
		if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTCOINEXPLORERMONK" ]; then
			echo "MONK EXPLORER AND COIN EXPLORER MONK = OK"
			# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND COIN EXPLORER MONK = OK;")
			BLOCKCOUNTCOINEXPLORERMONK=$[BLOCKCOUNTCOINEXPLORERMONK + 1]
		else
			echo "MONK EXPLORER AND COIN EXPLORER MONK NOT MATCH !!!"
			REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND COIN EXPLORER MONK NOT MATCH !!!;")
		fi
	fi	
fi

echo "*******************************************************"
echo **3. CHECKING MONK EXPLORER AND SEED ONE**
echo "BLOCKCOUNTMONKEXPLORER="$BLOCKCOUNTMONKEXPLORER
echo "BLOCKCOUNTMONKSEED_1="$BLOCKCOUNTMONKSEED_1
# BLOCKCOUNTMONKSEED_1=$[BLOCKCOUNTMONKSEED_1 + 2] # testing :)
if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTMONKSEED_1" ]; then
	echo "MONK EXPLORER AND SEED ONE = OK"
	# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND SEED ONE = OK;")
else
	BLOCKCOUNTMONKSEED_1=$[BLOCKCOUNTMONKSEED_1 + 1]
	if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTMONKSEED_1" ]; then
		echo "MONK EXPLORER AND SEED ONE = OK"
		# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND SEED ONE = OK;")
		BLOCKCOUNTMONKSEED_1=$[BLOCKCOUNTMONKSEED_1 - 1]
	else
		BLOCKCOUNTMONKSEED_1=$[BLOCKCOUNTMONKSEED_1 - 2]
		if [ "$BLOCKCOUNTMONKEXPLORER" == "$BLOCKCOUNTMONKSEED_1" ]; then
			echo "MONK EXPLORER AND SEED ONE = OK"
			# REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND SEED ONE = OK;")
			BLOCKCOUNTMONKSEED_1=$[BLOCKCOUNTMONKSEED_1 + 1]
		else
			echo "MONK EXPLORER AND SEED ONE NOT MATCH !!!"
			REPORTMAILBLOCKCOUNT=$REPORTMAILBLOCKCOUNT$(echo " ")$(echo "MONK EXPLORER AND SEED ONE NOT MATCH !!!;")
		fi
	fi	
fi
echo "*******************************************************"
# REPORTMAILBLOCKCOUNT="test"
echo $REPORTMAILBLOCKCOUNT
if [ -z "$REPORTMAILBLOCKCOUNT" ]; then
  echo "SEEDS AND EXPLORERS ARE ALL ON SAME BLOCK = OK"
else
  echo "SEEDS AND EXPLORERS ARE ALL ON SAME BLOCK NOT OK!!!"
  echo $REPORTMAILBLOCKCOUNT
fi